# Generated by Django 2.1.2 on 2018-10-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
